services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mahmoud
      - POSTGRES_PASSWORD=password123
    volumes:
      - fotleague-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mahmoud"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  fotleague-db: