services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mahmoud
      - POSTGRES_PASSWORD=password123
    volumes:
      - fotleague-db:/var/lib/postgresql/data

volumes:
  fotleague-db: