-- Create tables
CREATE TABLE IF NOT EXISTS roles(
    id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
    id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT UNIQUE NOT NULL,
    role INT NOT NULL REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS league_codes(
    id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS leagues(
    id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    owner_id INT NOT NULL REFERENCES users(id),
    code_id INT NOT NULL REFERENCES league_codes(id)
);

CREATE TABLE IF NOT EXISTS match_status(
    id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    match_status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS matches(
    id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    home TEXT NOT NULL,
    away TEXT NOT NULL,
    match_status INT NOT NULL REFERENCES match_status(id),
    home_score INT NULL,
    away_score INT NULL,
    season INT NOT NULL,
    datetime TIMESTAMP NOT NULL,
    gameweek INT NOT NULL,
    live_time TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS predictions(
    user_id INT NOT NULL REFERENCES users(id),
    match_id INT NOT NULL REFERENCES matches(id),
    home INT NOT NULL,
    away INT NOT NULL,
    PRIMARY KEY(user_id, match_id)
);

CREATE TABLE IF NOT EXISTS leagues_users(
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    league_id INT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    PRIMARY KEY(user_id, league_id)
);

CREATE TABLE IF NOT EXISTS scores(
    user_id INT NOT NULL REFERENCES users(id),
    match_id INT NOT NULL REFERENCES matches(id),
    score INT NOT NULL,
    PRIMARY KEY (user_id, match_id)
);

CREATE VIEW user_gameweek_scores AS
SELECT user_id, gameweek, SUM(score) AS score, season
        FROM matches LEFT JOIN scores
        ON scores.match_id = matches.id
        GROUP BY user_id, gameweek, season
        ORDER BY gameweek;

-- Insert data
INSERT INTO match_status(match_status) VALUES('upcoming'), ('in progress'), ('played'), ('aborted');

INSERT INTO roles(role) VALUES ('admin'), ('user');

INSERT INTO users(email, password, name, role) VALUES ('admin@admin.com', 'admin123', 'admin', 1);

INSERT INTO league_codes(code) VALUES('000000');

INSERT INTO leagues(name, owner_id, code_id) VALUES('global', 1, 1);

INSERT INTO leagues_users(user_id, league_id) VALUES (1, 1);