name: Build and Push Docker Images
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push backend
        id: build-push-backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: backend/Dockerfile
          push: true
          tags: mahmoudhamdy02/backend:latest

      - name: build and push scraping
        id: build-push-scraping
        uses: docker/build-push-action@v3
        with:
          context: ./scraping
          file: scraping/Dockerfile
          push: true
          tags: mahmoudhamdy02/scraping:latest

